### ISSUE TITLE
Dist version bundles moment

### ISSUE THREAD

**Issue by mdlawson** [headzoo/react-moment#13]
Despite moment being required as a peer dependency, this module will always bundle it's own version of moment when included via webpack etc. Though I don't think it would end up being used, moment is fairly large and bloats the bundle size. 

I haven't tested this out for sure, but I'm guessing moment is being required through moment-timezone, so you need to add moment-timezone as a peer dependency, and to the webpack externals configuration to prevent it being bundled.

**Comment by balupton** [comment]
yeah, this is quite the problem as it makes `react-moment/dist/index.js` a `202 KB` file.

I think I'll just have my component's render use moment directly

**Comment by headzoo** [comment]
Will get this worked out today.

**Comment by headzoo** [comment]
All fixed. The index.js in v0.1.3 is now a svelte 4.5k.

**Comment by balupton** [comment]
Thanks. That definitely reduced the duplication.

I ended up going with using https://github.com/taylorhakes/fecha directly, as it is only 1.87kb gzipped - whereas using this module which when one's app does its bundle, is significantly larger - even with locales removed - it seems the majority is due to the size of moment-timezone.

Posting here just for anyone else who may not need all the features of moment and looking for the smallest possible bundle size in their app.
